---
- name: Clone DevStack repository if not already present
  git:
    repo: "https://opendev.org/openstack/devstack.git"
    dest: /opt/devstack
    version: master
  become: yes

- name: Create DevStack configuration file from template
  template:
    src: local.conf.j2
    dest: /opt/devstack/local.conf
    mode: "0644"
  become: yes

- name: Check if the "stack" user exists
  command: id -u stack
  register: stack_user
  ignore_errors: yes

- name: Create "stack" user using DevStack tool if not present
  shell: "/opt/devstack/tools/create-stack-user.sh"
  args:
    chdir: /opt/devstack
  when: stack_user.rc != 0
  become: yes

- name: Run DevStack installation script as 'stack' user
  shell: "./stack.sh"
  args:
    chdir: /opt/devstack
  environment:
    DEVSTACK_HA: "true"  # Simulate HA by enabling multiple service processes
  become: yes
  become_user: stack
  register: devstack_install
  ignore_errors: yes

- name: Fail if DevStack installation failed
  fail:
    msg: "DevStack installation failed, rolling back deployment."
  when: devstack_install.rc != 0
