---
- name: Update apt cache and install required packages
  apt:
    update_cache: yes
    name:
      - git
      - python3-pip
      - docker.io
      - docker-compose
      - python3-openstackclient
      - rsyslog
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
